/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/customers": {
    get: {
      parameters: {
        query: {
          id: parameters["rowFilter.customers.id"];
          created_at:  parameters["rowFilter.customers.created_at"];
          first_name?: parameters["rowFilter.customers.first_name"];
          last_name?: parameters["rowFilter.customers.last_name"];
          phone_number?: parameters["rowFilter.customers.phone_number"];
          billing_address?:parameters["rowFilter.customers.billing_address"];
          shipping_address?:parameters["rowFilter.customers.shipping_address"];
          email?:parameters["rowFilter.customers.email"];
          imageUrl?:parameters["rowFilter.customers.imageUrl"];
          type?: parameters["rowFilter.customers.type"];
          business_name?:parameters["rowFilter.customers.business_name"];
          select?: parameters["select"];
          order?: parameters["order"];
          offset?: parameters["offset"];
          limit?: parameters["limit"];
          
        };
        header: {
          Range?: parameters["range"];
          "Range-Unit"?: parameters["rangeUnit"];
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["customers"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** customers */
          customers?: definitions["customers"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id: parameters["rowFilter.customers.id"];
          created_at:  parameters["rowFilter.customers.created_at"];
          first_name?: parameters["rowFilter.customers.first_name"];
          last_name?: parameters["rowFilter.customers.last_name"];
          phone_number?: parameters["rowFilter.customers.phone_number"];
          billing_address?:parameters["rowFilter.customers.billing_address"];
          shipping_address?:parameters["rowFilter.customers.shipping_address"];
          email?:parameters["rowFilter.customers.email"];
          imageUrl?:parameters["rowFilter.customers.imageUrl"];
          type?: parameters["rowFilter.customers.type"];
          business_name?:parameters["rowFilter.customers.business_name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id: parameters["rowFilter.customers.id"];
          created_at:  parameters["rowFilter.customers.created_at"];
          first_name?: parameters["rowFilter.customers.first_name"];
          last_name?: parameters["rowFilter.customers.last_name"];
          phone_number?: parameters["rowFilter.customers.phone_number"];
          billing_address?:parameters["rowFilter.customers.billing_address"];
          shipping_address?:parameters["rowFilter.customers.shipping_address"];
          email?:parameters["rowFilter.customers.email"];
          imageUrl?:parameters["rowFilter.customers.imageUrl"];
          type?: parameters["rowFilter.customers.type"];
          business_name?:parameters["rowFilter.customers.business_name"];
        };
        body: {
          /** customers */
          customers?: definitions["customers"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/orders": {
    get: {
      parameters: {
        query: {
          id: parameters["rowFilter.orders.id"];
          created_at:  parameters["rowFilter.orders.created_at"];
          customer_id?: parameters["rowFilter.orders.customer_id"];
          customer_name?: parameters["rowFilter.orders.customer_name"];
          customer_imageUrl?: parameters["rowFilter.orders.customer_imageUrl"];
          total_payment?: parameters["rowFilter.orders.total_payment"];
          payment_status_name?: parameters["rowFilter.orders.payment_status_name"];
          payment_status_id?: parameters["rowFilter.orders.payment_status_id"];
          status_id?:parameters["rowFilter.orders.status_id"];
          status_name?:parameters["rowFilter.orders.status_name"];
          tracking?:parameters["rowFilter.orders.tracking"];
          point_of_sale_id?:parameters["rowFilter.orders.point_of_sale_id"];
          pos_name?:parameters["rowFilter.orders.pos_name"];
          purchase_date?:parameters["rowFilter.orders.purchase_date"];
          item_count?: parameters["rowFilter.orders.item_count"];
          item_id?:parameters["rowFilter.orders.item_id"];
          item_ui_icon?:parameters["rowFilter.orders.item_ui_icon"];
          select?: parameters["select"];
          order?: parameters["order"];
          offset?: parameters["offset"];
          limit?: parameters["limit"];
          
        };
        header: {
          Range?: parameters["range"];
          "Range-Unit"?: parameters["rangeUnit"];
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["orders"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** customers */
          customers?: definitions["orders"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id: parameters["rowFilter.orders.id"];
          created_at:  parameters["rowFilter.orders.created_at"];
          customer_id?: parameters["rowFilter.orders.customer_id"];
          customer_name?: parameters["rowFilter.orders.customer_name"];
          customer_imageUrl?: parameters["rowFilter.orders.customer_imageUrl"];
          total_payment?: parameters["rowFilter.orders.total_payment"];
          payment_status_id?: parameters["rowFilter.orders.payment_status_id"];
          payment_status_name?: parameters["rowFilter.orders.payment_status_name"];
          status_id?:parameters["rowFilter.orders.status_id"];
          status_name?:parameters["rowFilter.orders.status_name"];
          tracking?:parameters["rowFilter.orders.tracking"];
          point_of_sale_id?:parameters["rowFilter.orders.point_of_sale_id"];
          pos_name?:parameters["rowFilter.orders.pos_name"];
          purchase_date?:parameters["rowFilter.orders.purchase_date"];
          item_count?: parameters["rowFilter.orders.item_count"];
          item_id?:parameters["rowFilter.orders.item_id"];
          item_ui_icon?:parameters["rowFilter.orders.item_ui_icon"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id: parameters["rowFilter.orders.id"];
          created_at:  parameters["rowFilter.orders.created_at"];
          customer_id?: parameters["rowFilter.orders.customer_id"];
          total_payment?: parameters["rowFilter.orders.total_payment"];
          customer_name?: parameters["rowFilter.orders.customer_name"];
          customer_imageUrl?: parameters["rowFilter.orders.customer_imageUrl"];
          payment_status_id?: parameters["rowFilter.orders.payment_status_id"];
          payment_status_name?: parameters["rowFilter.orders.payment_status_name"];
          status_id?:parameters["rowFilter.orders.status_id"];
          status_name?:parameters["rowFilter.orders.status_name"];
          tracking?:parameters["rowFilter.orders.tracking"];
          point_of_sale_id?:parameters["rowFilter.orders.point_of_sale_id"];
          pos_name?:parameters["rowFilter.orders.pos_name"];
          purchase_date?:parameters["rowFilter.orders.purchase_date"];
          item_count?: parameters["rowFilter.orders.item_count"];
          item_id?:parameters["rowFilter.orders.item_id"];
          item_ui_icon?:parameters["rowFilter.orders.item_ui_icon"];
        };
        body: {
          /** customers */
          customers?: definitions["orders"];
           /** orders */
           orders?: definitions["orders"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/products": {
    get: {
      parameters: {
        query: {
          id: parameters["rowFilter.products.id"];
          created_at:  parameters["rowFilter.products.created_at"];
          catalog?: parameters["rowFilter.products.catalog"];
          collection?: parameters["rowFilter.products.collection"];
          category?: parameters["rowFilter.products.category"];
          supplier?:parameters["rowFilter.products.supplier"];
          imageUrl?:parameters["rowFilter.products.imageUrl"];
          description?:parameters["rowFilter.products.description"];
          size?:parameters["rowFilter.products.size"];
          color?: parameters["rowFilter.products.color"];
          sku?:parameters["rowFilter.products.sku"];
          unit_cost?: parameters["rowFilter.products.unit_cost"];
          margin?: parameters["rowFilter.products.margin"];
          profit?:parameters["rowFilter.products.profit"];
          is_published?: parameters["rowFilter.products.is_published"];
          sale_price?: parameters["rowFilter.products.sale_price"];
          
          select?: parameters["select"];
          order?: parameters["order"];
          offset?: parameters["offset"];
          limit?: parameters["limit"];
        };
        header: {
          Range?: parameters["range"];
          "Range-Unit"?: parameters["rangeUnit"];
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["products"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** customers */
          customers?: definitions["products"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id: parameters["rowFilter.products.id"];
          created_at:  parameters["rowFilter.products.created_at"];
          catalog?: parameters["rowFilter.products.catalog"];
          collection?: parameters["rowFilter.products.collection"];
          category?: parameters["rowFilter.products.category"];
          supplier?:parameters["rowFilter.products.supplier"];
          imageUrl?:parameters["rowFilter.products.imageUrl"];
          description?:parameters["rowFilter.products.description"];
          size?:parameters["rowFilter.products.size"];
          color?: parameters["rowFilter.products.color"];
          sku?:parameters["rowFilter.products.sku"];
          unit_cost?: parameters["rowFilter.products.unit_cost"];
          margin?: parameters["rowFilter.products.margin"];
          profit?:parameters["rowFilter.products.profit"];
          is_published?: parameters["rowFilter.products.is_published"];
          sale_price?: parameters["rowFilter.products.sale_price"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id: parameters["rowFilter.products.id"];
          created_at:  parameters["rowFilter.products.created_at"];
          catalog?: parameters["rowFilter.products.catalog"];
          collection?: parameters["rowFilter.products.collection"];
          category?: parameters["rowFilter.products.category"];
          supplier?:parameters["rowFilter.products.supplier"];
          imageUrl?:parameters["rowFilter.products.imageUrl"];
          description?:parameters["rowFilter.products.description"];
          size?:parameters["rowFilter.products.size"];
          color?: parameters["rowFilter.products.color"];
          sku?:parameters["rowFilter.products.sku"];
          unit_cost?: parameters["rowFilter.products.unit_cost"];
          margin?: parameters["rowFilter.products.margin"];
          profit?:parameters["rowFilter.products.profit"];
          is_published?: parameters["rowFilter.products.is_published"];
          sale_price?: parameters["rowFilter.products.sale_price"];
        };
        body: {
          /** customers */
          customers?: definitions["products"];
           /** products */
           products?: definitions["products"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  customers: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: uuid */
    first_name: string;
    /** Format: text */
    last_name?: string;
    /** Format: text */
    phone_number?: string;
    billing_address?: string;
    shipping_address?: string;
    email?: string;
    business_name?: string;
    /** Format: text */
    imageUrl?: string;
    /**
     * Format: timestamp with time zone
     * @default (now() AT TIME ZONE 'utc'::text)
     */
    created_at?: string;
  };
  orders: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: uuid */
    customer_id: number;
    /** Format: text */
    total_payment?: string;
    /** Format: text */
    payment_status?: number;
    status_id?: number;
    tracking?: string;
    point_of_sale_id?: string;
    purchase_date?: string;
    /**
     * Format: timestamp with time zone
     * @default (now() AT TIME ZONE 'utc'::text)
     */
    created_at?: string;
  };
  products: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: uuid */
    catalog: number;
    /** Format: text */
    collection?: number;
    /** Format: text */
    category?: number;
    supplier?: number;
    imageUrl?: string;
    product_name?: string;
    description?: string;
    size?: string;
    color?: string;
    sku?: string;
    unit_cost?: number;
    sale_price?: number;
    margin?: number;
    profit?: number;
    is_published?: number;
    /**
     * Format: timestamp with time zone
     * @default (now() AT TIME ZONE 'utc'::text)
     */
    created_at?: string;
  };
}
export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description customers */
  "body.customers": definitions["customers"];
  "rowFilter.customers.id": string;
  "rowFilter.customers.first_name": string;
  "rowFilter.customers.last_name": string;
  "rowFilter.customers.phone_number": string;
  "rowFilter.customers.email": string;
  "rowFilter.customers.imageUrl": string;
  "rowFilter.customers.billing_address": string;
  "rowFilter.customers.shipping_address": string;
  "rowFilter.customers.type": string;
  "rowFilter.customers.business_name": string;
  "rowFilter.customers.created_at": string;
  /** @description orders */
  "body.orders": definitions["orders"];
  "rowFilter.orders.id": string;
  "rowFilter.orders.created_at": string;
  "rowFilter.orders.customer_id": string;
  "rowFilter.orders.customer_name": string;
  "rowFilter.orders.customer_imageUrl": string;
  "rowFilter.orders.total_payment": string;
  "rowFilter.orders.payment_status_id": string;
  "rowFilter.orders.payment_status_name": string;
  "rowFilter.orders.status_id": string;
  "rowFilter.orders.status_name": string;
  "rowFilter.orders.tracking": string;
  "rowFilter.orders.point_of_sale_id": string;
  "rowFilter.orders.pos_name": string;
  "rowFilter.orders.purchase_date": string;
  "rowFilter.orders.item_count": string;
  "rowFilter.orders.item_id": string;
  "rowFilter.orders.item_ui_icon": string;
   /** @description products */
   "body.products": definitions["products"];
   "rowFilter.products.id": string;
   "rowFilter.products.catalog": string;
   "rowFilter.products.collection": string;
   "rowFilter.products.category": string;
   "rowFilter.products.supplier": string;
   "rowFilter.products.imageUrl": string;
   "rowFilter.products.product_name": string;
   "rowFilter.products.description": string;
   "rowFilter.products.size": string;
   "rowFilter.products.color": string;
   "rowFilter.products.sku": string;
   "rowFilter.products.unit_cost": string;
   "rowFilter.products.sale_price": string;
   "rowFilter.products.margin": string;
   "rowFilter.products.profit": string;
   "rowFilter.products.is_published": string;
   "rowFilter.products.created_at": string;
}
export interface operations {}

export interface external {}
