// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: n7PMUCBoe1fA7rXcBRi5FH
// Component: 6rUEUjk3c5
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_club_debut_3_pl_app.module.css"; // plasmic-import: n7PMUCBoe1fA7rXcBRi5FH/projectcss
import sty from "./PlasmicMenuIcon.module.css"; // plasmic-import: 6rUEUjk3c5/css

import AppIcons7Icon from "./icons/PlasmicIcon__AppIcons7"; // plasmic-import: CWTyA7AvHz/icon

export type PlasmicMenuIcon__VariantMembers = {};

export type PlasmicMenuIcon__VariantsArgs = {};
type VariantPropType = keyof PlasmicMenuIcon__VariantsArgs;
export const PlasmicMenuIcon__VariantProps = new Array<VariantPropType>();

export type PlasmicMenuIcon__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicMenuIcon__ArgsType;
export const PlasmicMenuIcon__ArgProps = new Array<ArgPropType>("children");

export type PlasmicMenuIcon__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultMenuIconProps {
  children?: React.ReactNode;
  className?: string;
}

function PlasmicMenuIcon__RenderFunc(props: {
  variants: PlasmicMenuIcon__VariantsArgs;
  args: PlasmicMenuIcon__ArgsType;
  overrides: PlasmicMenuIcon__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      {p.renderPlasmicSlot({
        defaultContents: (
          <AppIcons7Icon
            className={classNames(projectcss.all, sty.svg__vb2Z)}
            role={"img"}
          />
        ),

        value: args.children
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMenuIcon__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMenuIcon__VariantsArgs;
    args?: PlasmicMenuIcon__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMenuIcon__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMenuIcon__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMenuIcon__ArgProps,
      internalVariantPropNames: PlasmicMenuIcon__VariantProps
    });

    return PlasmicMenuIcon__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMenuIcon";
  } else {
    func.displayName = `PlasmicMenuIcon.${nodeName}`;
  }
  return func;
}

export const PlasmicMenuIcon = Object.assign(
  // Top-level PlasmicMenuIcon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicMenuIcon
    internalVariantProps: PlasmicMenuIcon__VariantProps,
    internalArgProps: PlasmicMenuIcon__ArgProps
  }
);

export default PlasmicMenuIcon;
/* prettier-ignore-end */
