// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: n7PMUCBoe1fA7rXcBRi5FH
// Component: CUHfzwZLCQ
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: iZavS5akl9G/component

import { useScreenVariants as useScreenVariants_6JfnloVhzca } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 6JfnloVhzca/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_club_debut_3_pl_app.module.css"; // plasmic-import: n7PMUCBoe1fA7rXcBRi5FH/projectcss
import sty from "./PlasmicVerificationSuccessPage.module.css"; // plasmic-import: CUHfzwZLCQ/css

import LogoIcon from "./icons/PlasmicIcon__Logo"; // plasmic-import: mWQ8Pw_ze5N/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: dtW5sCNu7WP/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: zGfmmTFBuGj/icon

export type PlasmicVerificationSuccessPage__VariantMembers = {};

export type PlasmicVerificationSuccessPage__VariantsArgs = {};
type VariantPropType = keyof PlasmicVerificationSuccessPage__VariantsArgs;
export const PlasmicVerificationSuccessPage__VariantProps =
  new Array<VariantPropType>();

export type PlasmicVerificationSuccessPage__ArgsType = {};
type ArgPropType = keyof PlasmicVerificationSuccessPage__ArgsType;
export const PlasmicVerificationSuccessPage__ArgProps =
  new Array<ArgPropType>();

export type PlasmicVerificationSuccessPage__OverridesType = {
  root?: p.Flex<"div">;
  img?: p.Flex<typeof p.PlasmicImg>;
  freeBox?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
  h1?: p.Flex<"h1">;
  button?: p.Flex<typeof Button>;
  text?: p.Flex<"div">;
};

export interface DefaultVerificationSuccessPageProps {}

function PlasmicVerificationSuccessPage__RenderFunc(props: {
  variants: PlasmicVerificationSuccessPage__VariantsArgs;
  args: PlasmicVerificationSuccessPage__ArgsType;
  overrides: PlasmicVerificationSuccessPage__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_6JfnloVhzca()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{"Verification Success"}</title>
        <meta
          key="og:title"
          property="og:title"
          content={"Verification Success"}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <p.PlasmicImg
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={
              hasVariant(globalVariants, "screen", "mobile")
                ? ("1036.678px" as const)
                : ("1036.678px" as const)
            }
            displayMaxHeight={"none" as const}
            displayMaxWidth={
              hasVariant(globalVariants, "screen", "mobile")
                ? ("100%" as const)
                : ("100%" as const)
            }
            displayMinHeight={"0" as const}
            displayMinWidth={"0" as const}
            displayWidth={
              hasVariant(globalVariants, "screen", "mobile")
                ? ("642.909px" as const)
                : ("642.909px" as const)
            }
            loading={
              hasVariant(globalVariants, "screen", "mobile")
                ? ("lazy" as const)
                : ("lazy" as const)
            }
            src={
              hasVariant(globalVariants, "screen", "mobile")
                ? {
                    src: "/plasmic/club_debut_3_pl_app/images/group2.svg",
                    fullWidth: 642.909,
                    fullHeight: 1036.678,
                    aspectRatio: 0.679775
                  }
                : {
                    src: "/plasmic/club_debut_3_pl_app/images/group2.svg",
                    fullWidth: 642.909,
                    fullHeight: 1036.678,
                    aspectRatio: 0.679775
                  }
            }
          />

          <p.Stack
            as={"div"}
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox)}
          >
            <LogoIcon
              data-plasmic-name={"svg"}
              data-plasmic-override={overrides.svg}
              className={classNames(projectcss.all, sty.svg)}
              role={"img"}
            />

            <h1
              data-plasmic-name={"h1"}
              data-plasmic-override={overrides.h1}
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.__wab_text,
                sty.h1
              )}
            >
              {"Your email is comfirmed. Now go build your business!"}
            </h1>

            <Button
              data-plasmic-name={"button"}
              data-plasmic-override={overrides.button}
              className={classNames("__wab_instance", sty.button)}
              color={"orange" as const}
              showEndIcon={true}
            >
              <div
                data-plasmic-name={"text"}
                data-plasmic-override={overrides.text}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text
                )}
              >
                {"Button"}
              </div>
            </Button>
          </p.Stack>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img", "freeBox", "svg", "h1", "button", "text"],
  img: ["img"],
  freeBox: ["freeBox", "svg", "h1", "button", "text"],
  svg: ["svg"],
  h1: ["h1"],
  button: ["button", "text"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof p.PlasmicImg;
  freeBox: "div";
  svg: "svg";
  h1: "h1";
  button: typeof Button;
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicVerificationSuccessPage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicVerificationSuccessPage__VariantsArgs;
    args?: PlasmicVerificationSuccessPage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicVerificationSuccessPage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicVerificationSuccessPage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicVerificationSuccessPage__ArgProps,
      internalVariantPropNames: PlasmicVerificationSuccessPage__VariantProps
    });

    return PlasmicVerificationSuccessPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicVerificationSuccessPage";
  } else {
    func.displayName = `PlasmicVerificationSuccessPage.${nodeName}`;
  }
  return func;
}

export const PlasmicVerificationSuccessPage = Object.assign(
  // Top-level PlasmicVerificationSuccessPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    freeBox: makeNodeComponent("freeBox"),
    svg: makeNodeComponent("svg"),
    h1: makeNodeComponent("h1"),
    button: makeNodeComponent("button"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicVerificationSuccessPage
    internalVariantProps: PlasmicVerificationSuccessPage__VariantProps,
    internalArgProps: PlasmicVerificationSuccessPage__ArgProps
  }
);

export default PlasmicVerificationSuccessPage;
/* prettier-ignore-end */
