// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: n7PMUCBoe1fA7rXcBRi5FH
// Component: R4yARw0Col
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import SidePanel from "../../SidePanel"; // plasmic-import: 6cCQxsGyn8Z/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_club_debut_3_pl_app.module.css"; // plasmic-import: n7PMUCBoe1fA7rXcBRi5FH/projectcss
import sty from "./PlasmicProducts.module.css"; // plasmic-import: R4yARw0Col/css

export type PlasmicProducts__VariantMembers = {};

export type PlasmicProducts__VariantsArgs = {};
type VariantPropType = keyof PlasmicProducts__VariantsArgs;
export const PlasmicProducts__VariantProps = new Array<VariantPropType>();

export type PlasmicProducts__ArgsType = {};
type ArgPropType = keyof PlasmicProducts__ArgsType;
export const PlasmicProducts__ArgProps = new Array<ArgPropType>();

export type PlasmicProducts__OverridesType = {
  productsPage2?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
  sidePanel?: p.Flex<typeof SidePanel>;
  content?: p.Flex<"div">;
};

export interface DefaultProductsProps {}

function PlasmicProducts__RenderFunc(props: {
  variants: PlasmicProducts__VariantsArgs;
  args: PlasmicProducts__ArgsType;
  overrides: PlasmicProducts__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;

  return (
    <React.Fragment>
      {}

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        {true ? (
          <div
            data-plasmic-name={"productsPage2"}
            data-plasmic-override={overrides.productsPage2}
            data-plasmic-root={true}
            data-plasmic-for-node={forNode}
            className={classNames(
              projectcss.all,
              projectcss.root_reset,
              projectcss.plasmic_default_styles,
              projectcss.plasmic_mixins,
              projectcss.plasmic_tokens,
              sty.productsPage2
            )}
          >
            {true ? (
              <div
                data-plasmic-name={"freeBox"}
                data-plasmic-override={overrides.freeBox}
                className={classNames(projectcss.all, sty.freeBox)}
              >
                <SidePanel
                  data-plasmic-name={"sidePanel"}
                  data-plasmic-override={overrides.sidePanel}
                  className={classNames("__wab_instance", sty.sidePanel)}
                />

                <div
                  data-plasmic-name={"content"}
                  data-plasmic-override={overrides.content}
                  className={classNames(projectcss.all, sty.content)}
                />
              </div>
            ) : null}
          </div>
        ) : null}
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  productsPage2: ["productsPage2", "freeBox", "sidePanel", "content"],
  freeBox: ["freeBox", "sidePanel", "content"],
  sidePanel: ["sidePanel"],
  content: ["content"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  productsPage2: "div";
  freeBox: "div";
  sidePanel: typeof SidePanel;
  content: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProducts__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProducts__VariantsArgs;
    args?: PlasmicProducts__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicProducts__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicProducts__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicProducts__ArgProps,
      internalVariantPropNames: PlasmicProducts__VariantProps
    });

    return PlasmicProducts__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "productsPage2") {
    func.displayName = "PlasmicProducts";
  } else {
    func.displayName = `PlasmicProducts.${nodeName}`;
  }
  return func;
}

export const PlasmicProducts = Object.assign(
  // Top-level PlasmicProducts renders the root element
  makeNodeComponent("productsPage2"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    sidePanel: makeNodeComponent("sidePanel"),
    content: makeNodeComponent("content"),

    // Metadata about props expected for PlasmicProducts
    internalVariantProps: PlasmicProducts__VariantProps,
    internalArgProps: PlasmicProducts__ArgProps
  }
);

export default PlasmicProducts;
/* prettier-ignore-end */
