// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: n7PMUCBoe1fA7rXcBRi5FH
// Component: 7WRBgNlgYi
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_club_debut_3_pl_app.module.css"; // plasmic-import: n7PMUCBoe1fA7rXcBRi5FH/projectcss
import sty from "./PlasmicStatCardTitle.module.css"; // plasmic-import: 7WRBgNlgYi/css

export type PlasmicStatCardTitle__VariantMembers = {};

export type PlasmicStatCardTitle__VariantsArgs = {};
type VariantPropType = keyof PlasmicStatCardTitle__VariantsArgs;
export const PlasmicStatCardTitle__VariantProps = new Array<VariantPropType>();

export type PlasmicStatCardTitle__ArgsType = {
  title?: React.ReactNode;
};

type ArgPropType = keyof PlasmicStatCardTitle__ArgsType;
export const PlasmicStatCardTitle__ArgProps = new Array<ArgPropType>("title");

export type PlasmicStatCardTitle__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultStatCardTitleProps {
  title?: React.ReactNode;
  className?: string;
}

function PlasmicStatCardTitle__RenderFunc(props: {
  variants: PlasmicStatCardTitle__VariantsArgs;
  args: PlasmicStatCardTitle__ArgsType;
  overrides: PlasmicStatCardTitle__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      {p.renderPlasmicSlot({
        defaultContents: "All Orders",
        value: args.title,
        className: classNames(sty.slotTargetTitle)
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicStatCardTitle__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicStatCardTitle__VariantsArgs;
    args?: PlasmicStatCardTitle__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicStatCardTitle__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicStatCardTitle__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicStatCardTitle__ArgProps,
      internalVariantPropNames: PlasmicStatCardTitle__VariantProps
    });

    return PlasmicStatCardTitle__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicStatCardTitle";
  } else {
    func.displayName = `PlasmicStatCardTitle.${nodeName}`;
  }
  return func;
}

export const PlasmicStatCardTitle = Object.assign(
  // Top-level PlasmicStatCardTitle renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicStatCardTitle
    internalVariantProps: PlasmicStatCardTitle__VariantProps,
    internalArgProps: PlasmicStatCardTitle__ArgProps
  }
);

export default PlasmicStatCardTitle;
/* prettier-ignore-end */
